version: '3.9'

services:
  loadbalancer:
    container_name: loadbalancer
    image: loadbalancer:${APP_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile.nginx.prd
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx/certs:/etc/nginx/certs
      - ./volumes/nginx/templates:/etc/nginx/templates
      - ./volumes/nginx/webapps:/var/www/html
      - ./volumes/nginx/logs:/var/log/nginx
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-fpm
      - mysql
    networks:
      - net

  php-fpm:
    image: php:8.0-fpm
    restart: always
    volumes:
      - ./volumes/nginx/webapps:/var/www/html
      - ./config/php:/usr/local/etc/php
    depends_on:
      - mysql
    networks:
      - net
  
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CRBqsplaz#2024$
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    networks:
      - net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: CRBqsplaz#2024$
    depends_on:
      - mysql
    networks:
      - net

networks:
  net:
    driver: bridge
